/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.3
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/gradido-blockchain-js.h"

/* Class: CommunityRoot (_exports_CommunityRoot) */
// jsnapi_getclass
Napi::Function _exports_CommunityRoot_inst::GetClass(Napi::Env env) {
  std::map<std::string, _exports_CommunityRoot_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_exports_CommunityRoot_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_exports_CommunityRoot_inst>::DefineClass(env, "CommunityRoot", symbolTable);
}

void _exports_CommunityRoot_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _exports_CommunityRoot_templ::PropertyDescriptor> &members,
  std::map<std::string, _exports_CommunityRoot_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("getInvolvedAddresses");
  members.insert({
    "getInvolvedAddresses",
      _exports_CommunityRoot_templ::InstanceMethod("getInvolvedAddresses",
        &_exports_CommunityRoot_templ::_wrap_CommunityRoot_getInvolvedAddresses,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isInvolved");
  members.insert({
    "isInvolved",
      _exports_CommunityRoot_templ::InstanceMethod("isInvolved",
        &_exports_CommunityRoot_templ::_wrap_CommunityRoot_isInvolved,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_variable
  members.erase("pubkey");
  members.insert({
    "pubkey",
      _exports_CommunityRoot_templ::InstanceAccessor("pubkey",
        &_exports_CommunityRoot_templ::_wrap_CommunityRoot_pubkey_get,
        &_exports_CommunityRoot_templ::_wrap_CommunityRoot_pubkey_set,
        static_cast<napi_property_attributes>(napi_writable | napi_enumerable | napi_configurable))
    });
  // jsnapi_register_member_variable
  members.erase("gmwPubkey");
  members.insert({
    "gmwPubkey",
      _exports_CommunityRoot_templ::InstanceAccessor("gmwPubkey",
        &_exports_CommunityRoot_templ::_wrap_CommunityRoot_gmwPubkey_get,
        &_exports_CommunityRoot_templ::_wrap_CommunityRoot_gmwPubkey_set,
        static_cast<napi_property_attributes>(napi_writable | napi_enumerable | napi_configurable))
    });
  // jsnapi_register_member_variable
  members.erase("aufPubkey");
  members.insert({
    "aufPubkey",
      _exports_CommunityRoot_templ::InstanceAccessor("aufPubkey",
        &_exports_CommunityRoot_templ::_wrap_CommunityRoot_aufPubkey_get,
        &_exports_CommunityRoot_templ::_wrap_CommunityRoot_aufPubkey_set,
        static_cast<napi_property_attributes>(napi_writable | napi_enumerable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

