/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/gradido-blockchain-js.h"

/* Class: MemoryBlockPtr (_exports_MemoryBlockPtr) */
// jsnapi_getclass
Napi::Function _exports_MemoryBlockPtr_inst::GetClass(Napi::Env env) {
  std::map<std::string, _exports_MemoryBlockPtr_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_exports_MemoryBlockPtr_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_exports_MemoryBlockPtr_inst>::DefineClass(env, "MemoryBlockPtr", symbolTable);
}

void _exports_MemoryBlockPtr_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _exports_MemoryBlockPtr_templ::PropertyDescriptor> &members,
  std::map<std::string, _exports_MemoryBlockPtr_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("size");
  members.insert({
    "size",
      _exports_MemoryBlockPtr_templ::InstanceMethod("size",
        &_exports_MemoryBlockPtr_templ::_wrap_MemoryBlockPtr_size,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isNull");
  members.insert({
    "isNull",
      _exports_MemoryBlockPtr_templ::InstanceMethod("isNull",
        &_exports_MemoryBlockPtr_templ::_wrap_MemoryBlockPtr_isNull,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("data");
  members.insert({
    "data",
      _exports_MemoryBlockPtr_templ::InstanceMethod("data",
        &_exports_MemoryBlockPtr_templ::_wrap_MemoryBlockPtr_data,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("get");
  members.insert({
    "get",
      _exports_MemoryBlockPtr_templ::InstanceMethod("get",
        &_exports_MemoryBlockPtr_templ::_wrap_MemoryBlockPtr_get,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("convertToHex");
  members.insert({
    "convertToHex",
      _exports_MemoryBlockPtr_templ::InstanceMethod("convertToHex",
        &_exports_MemoryBlockPtr_templ::_wrap_MemoryBlockPtr_convertToHex,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("convertToBase64");
  members.insert({
    "convertToBase64",
      _exports_MemoryBlockPtr_templ::InstanceMethod("convertToBase64",
        &_exports_MemoryBlockPtr_templ::_wrap_MemoryBlockPtr_convertToBase64,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("copyAsString");
  members.insert({
    "copyAsString",
      _exports_MemoryBlockPtr_templ::InstanceMethod("copyAsString",
        &_exports_MemoryBlockPtr_templ::_wrap_MemoryBlockPtr_copyAsString,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isEmpty");
  members.insert({
    "isEmpty",
      _exports_MemoryBlockPtr_templ::InstanceMethod("isEmpty",
        &_exports_MemoryBlockPtr_templ::_wrap_MemoryBlockPtr_isEmpty,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("equal");
  members.insert({
    "equal",
      _exports_MemoryBlockPtr_templ::InstanceMethod("equal",
        &_exports_MemoryBlockPtr_templ::_wrap_MemoryBlockPtr__wrap_MemoryBlockPtr_equal,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("notEqual");
  members.insert({
    "notEqual",
      _exports_MemoryBlockPtr_templ::InstanceMethod("notEqual",
        &_exports_MemoryBlockPtr_templ::_wrap_MemoryBlockPtr__wrap_MemoryBlockPtr_notEqual,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("lt");
  members.insert({
    "lt",
      _exports_MemoryBlockPtr_templ::InstanceMethod("lt",
        &_exports_MemoryBlockPtr_templ::_wrap_MemoryBlockPtr__wrap_MemoryBlockPtr_lt,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_variable
  members.erase("mBlock");
  members.insert({
    "mBlock",
      _exports_MemoryBlockPtr_templ::InstanceAccessor("mBlock",
        &_exports_MemoryBlockPtr_templ::_wrap_MemoryBlockPtr_mBlock_get,
        &_exports_MemoryBlockPtr_templ::_wrap_MemoryBlockPtr_mBlock_set,
        static_cast<napi_property_attributes>(napi_writable | napi_enumerable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

