/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.3
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/gradido-blockchain-js.h"

/* Class: InMemoryBlockchainProvider (_exports_InMemoryBlockchainProvider) */
// jsnapi_getclass
Napi::Function _exports_InMemoryBlockchainProvider_inst::GetClass(Napi::Env env) {
  std::map<std::string, _exports_InMemoryBlockchainProvider_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_exports_InMemoryBlockchainProvider_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_exports_InMemoryBlockchainProvider_inst>::DefineClass(env, "InMemoryBlockchainProvider", symbolTable);
}

void _exports_InMemoryBlockchainProvider_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _exports_InMemoryBlockchainProvider_templ::PropertyDescriptor> &members,
  std::map<std::string, _exports_InMemoryBlockchainProvider_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("clear");
  members.insert({
    "clear",
      _exports_InMemoryBlockchainProvider_templ::InstanceMethod("clear",
        &_exports_InMemoryBlockchainProvider_templ::_wrap_InMemoryBlockchainProvider_clear,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getBlockchain");
  members.insert({
    "getBlockchain",
      _exports_InMemoryBlockchainProvider_templ::InstanceMethod("getBlockchain",
        &_exports_InMemoryBlockchainProvider_templ::_wrap_InMemoryBlockchainProvider_getBlockchain,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  /* add static class functions and variables */
  // jsnapi_register_static_function
  staticMembers.erase("getInstance");
  staticMembers.insert({
    "getInstance",
      StaticMethod("getInstance",
        &_exports_InMemoryBlockchainProvider_templ::_wrap_InMemoryBlockchainProvider_getInstance,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

