/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/gradido-blockchain-js.h"

/* Class: InMemoryBlockchain (_exports_InMemoryBlockchain) */
// jsnapi_getclass
Napi::Function _exports_InMemoryBlockchain_inst::GetClass(Napi::Env env) {
  std::map<std::string, _exports_InMemoryBlockchain_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_exports_InMemoryBlockchain_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_exports_InMemoryBlockchain_inst>::DefineClass(env, "InMemoryBlockchain", symbolTable);
}

void _exports_InMemoryBlockchain_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _exports_InMemoryBlockchain_templ::PropertyDescriptor> &members,
  std::map<std::string, _exports_InMemoryBlockchain_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, _exports_Abstract_templ<_exports_Abstract_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  _exports_Abstract_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("createAndAddConfirmedTransaction");
  members.insert({
    "createAndAddConfirmedTransaction",
      _exports_Abstract_templ::InstanceMethod("createAndAddConfirmedTransaction",
        &_exports_Abstract_templ::_wrap_Abstract_createAndAddConfirmedTransaction,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("addTransactionTriggerEvent");
  members.insert({
    "addTransactionTriggerEvent",
      _exports_Abstract_templ::InstanceMethod("addTransactionTriggerEvent",
        &_exports_Abstract_templ::_wrap_Abstract_addTransactionTriggerEvent,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("removeTransactionTriggerEvent");
  members.insert({
    "removeTransactionTriggerEvent",
      _exports_Abstract_templ::InstanceMethod("removeTransactionTriggerEvent",
        &_exports_Abstract_templ::_wrap_Abstract_removeTransactionTriggerEvent,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isTransactionExist");
  members.insert({
    "isTransactionExist",
      _exports_Abstract_templ::InstanceMethod("isTransactionExist",
        &_exports_Abstract_templ::_wrap_Abstract_isTransactionExist,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("findTransactionTriggerEventsInRange");
  members.insert({
    "findTransactionTriggerEventsInRange",
      _exports_Abstract_templ::InstanceMethod("findTransactionTriggerEventsInRange",
        &_exports_Abstract_templ::_wrap_Abstract_findTransactionTriggerEventsInRange,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("findAll");
  members.insert({
    "findAll",
      _exports_Abstract_templ::InstanceMethod("findAll",
        &_exports_Abstract_templ::_wrap_Abstract__wrap_Abstract_findAll,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("findOne");
  members.insert({
    "findOne",
      _exports_Abstract_templ::InstanceMethod("findOne",
        &_exports_Abstract_templ::_wrap_Abstract__wrap_Abstract_findOne,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getAddressType");
  members.insert({
    "getAddressType",
      _exports_Abstract_templ::InstanceMethod("getAddressType",
        &_exports_Abstract_templ::_wrap_Abstract__wrap_Abstract_getAddressType,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getTransactionForId");
  members.insert({
    "getTransactionForId",
      _exports_Abstract_templ::InstanceMethod("getTransactionForId",
        &_exports_Abstract_templ::_wrap_Abstract_getTransactionForId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("findByMessageId");
  members.insert({
    "findByMessageId",
      _exports_Abstract_templ::InstanceMethod("findByMessageId",
        &_exports_Abstract_templ::_wrap_Abstract__wrap_Abstract_findByMessageId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getCommunityId");
  members.insert({
    "getCommunityId",
      _exports_Abstract_templ::InstanceMethod("getCommunityId",
        &_exports_Abstract_templ::_wrap_Abstract_getCommunityId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getStartDate");
  members.insert({
    "getStartDate",
      _exports_Abstract_templ::InstanceMethod("getStartDate",
        &_exports_Abstract_templ::_wrap_Abstract_getStartDate,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("clear");
  members.insert({
    "clear",
      _exports_InMemoryBlockchain_templ::InstanceMethod("clear",
        &_exports_InMemoryBlockchain_templ::_wrap_InMemoryBlockchain_clear,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("exit");
  members.insert({
    "exit",
      _exports_InMemoryBlockchain_templ::InstanceMethod("exit",
        &_exports_InMemoryBlockchain_templ::_wrap_InMemoryBlockchain_exit,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("createAndAddConfirmedTransaction");
  members.insert({
    "createAndAddConfirmedTransaction",
      _exports_InMemoryBlockchain_templ::InstanceMethod("createAndAddConfirmedTransaction",
        &_exports_InMemoryBlockchain_templ::_wrap_InMemoryBlockchain_createAndAddConfirmedTransaction,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("addTransactionTriggerEvent");
  members.insert({
    "addTransactionTriggerEvent",
      _exports_InMemoryBlockchain_templ::InstanceMethod("addTransactionTriggerEvent",
        &_exports_InMemoryBlockchain_templ::_wrap_InMemoryBlockchain_addTransactionTriggerEvent,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("removeTransactionTriggerEvent");
  members.insert({
    "removeTransactionTriggerEvent",
      _exports_InMemoryBlockchain_templ::InstanceMethod("removeTransactionTriggerEvent",
        &_exports_InMemoryBlockchain_templ::_wrap_InMemoryBlockchain_removeTransactionTriggerEvent,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isTransactionExist");
  members.insert({
    "isTransactionExist",
      _exports_InMemoryBlockchain_templ::InstanceMethod("isTransactionExist",
        &_exports_InMemoryBlockchain_templ::_wrap_InMemoryBlockchain_isTransactionExist,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("findTransactionTriggerEventsInRange");
  members.insert({
    "findTransactionTriggerEventsInRange",
      _exports_InMemoryBlockchain_templ::InstanceMethod("findTransactionTriggerEventsInRange",
        &_exports_InMemoryBlockchain_templ::_wrap_InMemoryBlockchain_findTransactionTriggerEventsInRange,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getSortedTransactions");
  members.insert({
    "getSortedTransactions",
      _exports_InMemoryBlockchain_templ::InstanceMethod("getSortedTransactions",
        &_exports_InMemoryBlockchain_templ::_wrap_InMemoryBlockchain_getSortedTransactions,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("findAll");
  members.insert({
    "findAll",
      _exports_InMemoryBlockchain_templ::InstanceMethod("findAll",
        &_exports_InMemoryBlockchain_templ::_wrap_InMemoryBlockchain__wrap_InMemoryBlockchain_findAll,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getTransactionForId");
  members.insert({
    "getTransactionForId",
      _exports_InMemoryBlockchain_templ::InstanceMethod("getTransactionForId",
        &_exports_InMemoryBlockchain_templ::_wrap_InMemoryBlockchain_getTransactionForId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("findByMessageId");
  members.insert({
    "findByMessageId",
      _exports_InMemoryBlockchain_templ::InstanceMethod("findByMessageId",
        &_exports_InMemoryBlockchain_templ::_wrap_InMemoryBlockchain__wrap_InMemoryBlockchain_findByMessageId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

