/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/gradido-blockchain-js.h"

/* Class: InteractionCalculateAccountBalance (_exports_InteractionCalculateAccountBalance) */
// jsnapi_getclass
Napi::Function _exports_InteractionCalculateAccountBalance_inst::GetClass(Napi::Env env) {
  std::map<std::string, _exports_InteractionCalculateAccountBalance_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_exports_InteractionCalculateAccountBalance_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_exports_InteractionCalculateAccountBalance_inst>::DefineClass(env, "InteractionCalculateAccountBalance", symbolTable);
}

void _exports_InteractionCalculateAccountBalance_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _exports_InteractionCalculateAccountBalance_templ::PropertyDescriptor> &members,
  std::map<std::string, _exports_InteractionCalculateAccountBalance_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("fromBegin");
  members.insert({
    "fromBegin",
      _exports_InteractionCalculateAccountBalance_templ::InstanceMethod("fromBegin",
        &_exports_InteractionCalculateAccountBalance_templ::_wrap_InteractionCalculateAccountBalance__wrap_InteractionCalculateAccountBalance_fromBegin,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("fromEnd");
  members.insert({
    "fromEnd",
      _exports_InteractionCalculateAccountBalance_templ::InstanceMethod("fromEnd",
        &_exports_InteractionCalculateAccountBalance_templ::_wrap_InteractionCalculateAccountBalance__wrap_InteractionCalculateAccountBalance_fromEnd,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

