/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.3
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/gradido-blockchain-js.h"

/* Class: TransferAmount (_exports_TransferAmount) */
// jsnapi_getclass
Napi::Function _exports_TransferAmount_inst::GetClass(Napi::Env env) {
  std::map<std::string, _exports_TransferAmount_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_exports_TransferAmount_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_exports_TransferAmount_inst>::DefineClass(env, "TransferAmount", symbolTable);
}

void _exports_TransferAmount_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _exports_TransferAmount_templ::PropertyDescriptor> &members,
  std::map<std::string, _exports_TransferAmount_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("equal");
  members.insert({
    "equal",
      _exports_TransferAmount_templ::InstanceMethod("equal",
        &_exports_TransferAmount_templ::_wrap_TransferAmount_equal,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getPubkey");
  members.insert({
    "getPubkey",
      _exports_TransferAmount_templ::InstanceMethod("getPubkey",
        &_exports_TransferAmount_templ::_wrap_TransferAmount_getPubkey,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getAmount");
  members.insert({
    "getAmount",
      _exports_TransferAmount_templ::InstanceMethod("getAmount",
        &_exports_TransferAmount_templ::_wrap_TransferAmount_getAmount,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getCommunityId");
  members.insert({
    "getCommunityId",
      _exports_TransferAmount_templ::InstanceMethod("getCommunityId",
        &_exports_TransferAmount_templ::_wrap_TransferAmount_getCommunityId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

