/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.3
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/gradido-blockchain-js.h"

/* Class: RegisterAddress (_exports_RegisterAddress) */
// jsnapi_getclass
Napi::Function _exports_RegisterAddress_inst::GetClass(Napi::Env env) {
  std::map<std::string, _exports_RegisterAddress_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_exports_RegisterAddress_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_exports_RegisterAddress_inst>::DefineClass(env, "RegisterAddress", symbolTable);
}

void _exports_RegisterAddress_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _exports_RegisterAddress_templ::PropertyDescriptor> &members,
  std::map<std::string, _exports_RegisterAddress_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("equal");
  members.insert({
    "equal",
      _exports_RegisterAddress_templ::InstanceMethod("equal",
        &_exports_RegisterAddress_templ::_wrap_RegisterAddress_equal,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getInvolvedAddresses");
  members.insert({
    "getInvolvedAddresses",
      _exports_RegisterAddress_templ::InstanceMethod("getInvolvedAddresses",
        &_exports_RegisterAddress_templ::_wrap_RegisterAddress_getInvolvedAddresses,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isInvolved");
  members.insert({
    "isInvolved",
      _exports_RegisterAddress_templ::InstanceMethod("isInvolved",
        &_exports_RegisterAddress_templ::_wrap_RegisterAddress_isInvolved,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getUserPublicKey");
  members.insert({
    "getUserPublicKey",
      _exports_RegisterAddress_templ::InstanceMethod("getUserPublicKey",
        &_exports_RegisterAddress_templ::_wrap_RegisterAddress_getUserPublicKey,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getAddressType");
  members.insert({
    "getAddressType",
      _exports_RegisterAddress_templ::InstanceMethod("getAddressType",
        &_exports_RegisterAddress_templ::_wrap_RegisterAddress_getAddressType,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getNameHash");
  members.insert({
    "getNameHash",
      _exports_RegisterAddress_templ::InstanceMethod("getNameHash",
        &_exports_RegisterAddress_templ::_wrap_RegisterAddress_getNameHash,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getAccountPublicKey");
  members.insert({
    "getAccountPublicKey",
      _exports_RegisterAddress_templ::InstanceMethod("getAccountPublicKey",
        &_exports_RegisterAddress_templ::_wrap_RegisterAddress_getAccountPublicKey,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getDerivationIndex");
  members.insert({
    "getDerivationIndex",
      _exports_RegisterAddress_templ::InstanceMethod("getDerivationIndex",
        &_exports_RegisterAddress_templ::_wrap_RegisterAddress_getDerivationIndex,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

