/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/gradido-blockchain-js.h"

/* Class: HieroTransactionIdCompact (_exports_HieroTransactionIdCompact) */
// jsnapi_getclass
Napi::Function _exports_HieroTransactionIdCompact_inst::GetClass(Napi::Env env) {
  std::map<std::string, _exports_HieroTransactionIdCompact_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_exports_HieroTransactionIdCompact_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_exports_HieroTransactionIdCompact_inst>::DefineClass(env, "HieroTransactionIdCompact", symbolTable);
}

void _exports_HieroTransactionIdCompact_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _exports_HieroTransactionIdCompact_templ::PropertyDescriptor> &members,
  std::map<std::string, _exports_HieroTransactionIdCompact_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_variable
  members.erase("seconds");
  members.insert({
    "seconds",
      _exports_HieroTransactionIdCompact_templ::InstanceAccessor("seconds",
        &_exports_HieroTransactionIdCompact_templ::_wrap_HieroTransactionIdCompact_seconds_get,
        &_exports_HieroTransactionIdCompact_templ::_wrap_HieroTransactionIdCompact_seconds_set,
        static_cast<napi_property_attributes>(napi_writable | napi_enumerable | napi_configurable))
    });
  // jsnapi_register_member_variable
  members.erase("nanos");
  members.insert({
    "nanos",
      _exports_HieroTransactionIdCompact_templ::InstanceAccessor("nanos",
        &_exports_HieroTransactionIdCompact_templ::_wrap_HieroTransactionIdCompact_nanos_get,
        &_exports_HieroTransactionIdCompact_templ::_wrap_HieroTransactionIdCompact_nanos_set,
        static_cast<napi_property_attributes>(napi_writable | napi_enumerable | napi_configurable))
    });
  // jsnapi_register_member_variable
  members.erase("accountNum");
  members.insert({
    "accountNum",
      _exports_HieroTransactionIdCompact_templ::InstanceAccessor("accountNum",
        &_exports_HieroTransactionIdCompact_templ::_wrap_HieroTransactionIdCompact_accountNum_get,
        &_exports_HieroTransactionIdCompact_templ::_wrap_HieroTransactionIdCompact_accountNum_set,
        static_cast<napi_property_attributes>(napi_writable | napi_enumerable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("equal");
  members.insert({
    "equal",
      _exports_HieroTransactionIdCompact_templ::InstanceMethod("equal",
        &_exports_HieroTransactionIdCompact_templ::_wrap_HieroTransactionIdCompact_equal,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

