/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.3
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/gradido-blockchain-js.h"


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static void *_p_DecryptionExceptionTo_p_SecretKeyCryptographyException(void *x, int *SWIGUNUSEDPARM(newmemory)) {
    return (void *)((SecretKeyCryptographyException *)  ((DecryptionException *) x));
}
static void *_p_EncryptionExceptionTo_p_SecretKeyCryptographyException(void *x, int *SWIGUNUSEDPARM(newmemory)) {
    return (void *)((SecretKeyCryptographyException *)  ((EncryptionException *) x));
}
static void *_p_EncryptionKeyExceptionTo_p_SecretKeyCryptographyException(void *x, int *SWIGUNUSEDPARM(newmemory)) {
    return (void *)((SecretKeyCryptographyException *)  ((EncryptionKeyException *) x));
}
static void *_p_MissingEncryptionExceptionTo_p_SecretKeyCryptographyException(void *x, int *SWIGUNUSEDPARM(newmemory)) {
    return (void *)((SecretKeyCryptographyException *)  ((MissingEncryptionException *) x));
}
SWIGINTERN swig_type_info _swigt__p_GradidoUnit = {"_p_GradidoUnit", "p_GradidoUnit|GradidoUnit *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_SecretKeyCryptography = {"_p_SecretKeyCryptography", "p_SecretKeyCryptography|SecretKeyCryptography *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_SecretKeyCryptographyException = {"_p_SecretKeyCryptographyException", "SecretKeyCryptographyException *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_DecryptionException = {"_p_DecryptionException", 0, 0, 0, 0, 0};
SWIGINTERN swig_type_info _swigt__p_EncryptionException = {"_p_EncryptionException", 0, 0, 0, 0, 0};
SWIGINTERN swig_type_info _swigt__p_EncryptionKeyException = {"_p_EncryptionKeyException", 0, 0, 0, 0, 0};
SWIGINTERN swig_type_info _swigt__p_MissingEncryptionException = {"_p_MissingEncryptionException", 0, 0, 0, 0, 0};
SWIGINTERN swig_type_info _swigt__p_char = {"_p_char", "char *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_gradido__GradidoTransactionBuilder = {"_p_gradido__GradidoTransactionBuilder", "p_gradido__GradidoTransactionBuilder|gradido::GradidoTransactionBuilder *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_gradido__TransactionBodyBuilder = {"_p_gradido__TransactionBodyBuilder", "p_gradido__TransactionBodyBuilder|gradido::TransactionBodyBuilder *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_gradido__data__CommunityFriendsUpdate = {"_p_gradido__data__CommunityFriendsUpdate", "p_gradido__data__CommunityFriendsUpdate|gradido::data::CommunityFriendsUpdate *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_gradido__data__CommunityRoot = {"_p_gradido__data__CommunityRoot", "p_gradido__data__CommunityRoot|gradido::data::CommunityRoot *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_gradido__data__ConfirmedTransaction = {"_p_gradido__data__ConfirmedTransaction", "p_gradido__data__ConfirmedTransaction|gradido::data::ConfirmedTransaction *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_gradido__data__GradidoCreation = {"_p_gradido__data__GradidoCreation", "p_gradido__data__GradidoCreation|gradido::data::GradidoCreation *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_gradido__data__GradidoDeferredTransfer = {"_p_gradido__data__GradidoDeferredTransfer", "p_gradido__data__GradidoDeferredTransfer|gradido::data::GradidoDeferredTransfer *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_gradido__data__GradidoTransaction = {"_p_gradido__data__GradidoTransaction", "p_gradido__data__GradidoTransaction|gradido::data::GradidoTransaction *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_gradido__data__GradidoTransfer = {"_p_gradido__data__GradidoTransfer", "gradido::data::GradidoTransfer *|p_gradido__data__GradidoTransfer", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_gradido__data__RegisterAddress = {"_p_gradido__data__RegisterAddress", "gradido::data::RegisterAddress *|p_gradido__data__RegisterAddress", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_gradido__data__SignatureMap = {"_p_gradido__data__SignatureMap", "gradido::data::SignatureMap *|p_gradido__data__SignatureMap", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_gradido__data__SignaturePair = {"_p_gradido__data__SignaturePair", "p_gradido__data__SignaturePair|gradido::data::SignaturePair *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_gradido__data__Timestamp = {"_p_gradido__data__Timestamp", "p_gradido__data__Timestamp|gradido::data::Timestamp *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_gradido__data__TimestampSeconds = {"_p_gradido__data__TimestampSeconds", "gradido::data::TimestampSeconds *|p_gradido__data__TimestampSeconds", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_gradido__data__TransactionBody = {"_p_gradido__data__TransactionBody", "gradido::data::TransactionBody *|p_gradido__data__TransactionBody", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_gradido__data__TransferAmount = {"_p_gradido__data__TransferAmount", "gradido::data::TransferAmount *|p_gradido__data__TransferAmount", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_int = {"_p_int", "int32_t *|int_fast16_t *|int_fast32_t *|int_least32_t *|intptr_t *|int *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_long_long = {"_p_long_long", "int64_t *|int_fast64_t *|int_least64_t *|intmax_t *|long long *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_memory__Block = {"_p_memory__Block", "MemoryBin *|p_memory__Block|memory::Block *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_memory__ConstBlockPtrComparator = {"_p_memory__ConstBlockPtrComparator", "p_memory__ConstBlockPtrComparator|memory::ConstBlockPtrComparator *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_short = {"_p_short", "int16_t *|int_least16_t *|short *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_signed_char = {"_p_signed_char", "int8_t *|int_fast8_t *|int_least8_t *|signed char *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__chrono__system_clock__duration = {"_p_std__chrono__system_clock__duration", "Duration *|std::chrono::system_clock::duration *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__chrono__time_pointT_std__chrono__system_clock_t = {"_p_std__chrono__time_pointT_std__chrono__system_clock_t", "Timepoint *|std::chrono::time_point< std::chrono::system_clock > *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__shared_ptrT_KeyPairEd25519_t = {"_p_std__shared_ptrT_KeyPairEd25519_t", "std::shared_ptr< KeyPairEd25519 > *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__shared_ptrT_SecretKeyCryptography_t = {"_p_std__shared_ptrT_SecretKeyCryptography_t", "std::shared_ptr< SecretKeyCryptography > *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__shared_ptrT_gradido__data__CommunityFriendsUpdate_t = {"_p_std__shared_ptrT_gradido__data__CommunityFriendsUpdate_t", "std::shared_ptr< gradido::data::CommunityFriendsUpdate > *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__shared_ptrT_gradido__data__CommunityRoot_t = {"_p_std__shared_ptrT_gradido__data__CommunityRoot_t", "std::shared_ptr< gradido::data::CommunityRoot > *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__shared_ptrT_gradido__data__ConfirmedTransaction_const_t = {"_p_std__shared_ptrT_gradido__data__ConfirmedTransaction_const_t", "gradido::data::ConstConfirmedTransactionPtr *|std::shared_ptr< gradido::data::ConfirmedTransaction const > *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__shared_ptrT_gradido__data__ConfirmedTransaction_t = {"_p_std__shared_ptrT_gradido__data__ConfirmedTransaction_t", "gradido::data::ConfirmedTransactionPtr *|std::shared_ptr< gradido::data::ConfirmedTransaction > *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__shared_ptrT_gradido__data__GradidoCreation_t = {"_p_std__shared_ptrT_gradido__data__GradidoCreation_t", "std::shared_ptr< gradido::data::GradidoCreation > *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__shared_ptrT_gradido__data__GradidoDeferredTransfer_t = {"_p_std__shared_ptrT_gradido__data__GradidoDeferredTransfer_t", "std::shared_ptr< gradido::data::GradidoDeferredTransfer > *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__shared_ptrT_gradido__data__GradidoTransaction_const_t = {"_p_std__shared_ptrT_gradido__data__GradidoTransaction_const_t", "gradido::data::ConstGradidoTransactionPtr *|std::shared_ptr< gradido::data::GradidoTransaction const > *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__shared_ptrT_gradido__data__GradidoTransfer_t = {"_p_std__shared_ptrT_gradido__data__GradidoTransfer_t", "std::shared_ptr< gradido::data::GradidoTransfer > *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__shared_ptrT_gradido__data__RegisterAddress_t = {"_p_std__shared_ptrT_gradido__data__RegisterAddress_t", "std::shared_ptr< gradido::data::RegisterAddress > *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__shared_ptrT_gradido__data__TransactionBody_const_t = {"_p_std__shared_ptrT_gradido__data__TransactionBody_const_t", "gradido::data::ConstTransactionBodyPtr *|std::shared_ptr< gradido::data::TransactionBody const > *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__shared_ptrT_memory__Block_const_t = {"_p_std__shared_ptrT_memory__Block_const_t", "memory::ConstBlockPtr *|std::shared_ptr< memory::Block const > *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__shared_ptrT_memory__Block_t = {"_p_std__shared_ptrT_memory__Block_t", "memory::BlockPtr *|std::shared_ptr< memory::Block > *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__spanT_std__byte_t = {"_p_std__spanT_std__byte_t", "std::span< std::byte > *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__string = {"_p_std__string", "std::string *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__vectorT_gradido__data__SignaturePair_t = {"_p_std__vectorT_gradido__data__SignaturePair_t", "std::vector< gradido::data::SignaturePair > *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__vectorT_std__shared_ptrT_memory__Block_const_t_t = {"_p_std__vectorT_std__shared_ptrT_memory__Block_const_t_t", "std::vector< memory::ConstBlockPtr > *|std::vector< std::shared_ptr< memory::Block const > > *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_std__vectorT_unsigned_char_t = {"_p_std__vectorT_unsigned_char_t", "std::vector< uint8_t > *|std::vector< unsigned char > *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_unsigned_char = {"_p_unsigned_char", "uint8_t *|uint_fast8_t *|uint_least8_t *|unsigned char *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_unsigned_int = {"_p_unsigned_int", "uint32_t *|uint_fast16_t *|uint_fast32_t *|uint_least32_t *|uintptr_t *|unsigned int *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_unsigned_long_long = {"_p_unsigned_long_long", "KeyHashed *|uint64_t *|uint_fast64_t *|uint_least64_t *|uintmax_t *|unsigned long long *", 0, 0, (void*)0, 0};
SWIGINTERN swig_type_info _swigt__p_unsigned_short = {"_p_unsigned_short", "uint16_t *|uint_least16_t *|unsigned short *", 0, 0, (void*)0, 0};

SWIGINTERN swig_type_info *swig_type_initial[] = {

/* -------- TYPES TABLE (BEGIN) -------- */

  &_swigt__p_DecryptionException,
  &_swigt__p_EncryptionException,
  &_swigt__p_EncryptionKeyException,
  &_swigt__p_GradidoUnit,
  &_swigt__p_MissingEncryptionException,
  &_swigt__p_SecretKeyCryptography,
  &_swigt__p_SecretKeyCryptographyException,
  &_swigt__p_char,
  &_swigt__p_gradido__GradidoTransactionBuilder,
  &_swigt__p_gradido__TransactionBodyBuilder,
  &_swigt__p_gradido__data__CommunityFriendsUpdate,
  &_swigt__p_gradido__data__CommunityRoot,
  &_swigt__p_gradido__data__ConfirmedTransaction,
  &_swigt__p_gradido__data__GradidoCreation,
  &_swigt__p_gradido__data__GradidoDeferredTransfer,
  &_swigt__p_gradido__data__GradidoTransaction,
  &_swigt__p_gradido__data__GradidoTransfer,
  &_swigt__p_gradido__data__RegisterAddress,
  &_swigt__p_gradido__data__SignatureMap,
  &_swigt__p_gradido__data__SignaturePair,
  &_swigt__p_gradido__data__Timestamp,
  &_swigt__p_gradido__data__TimestampSeconds,
  &_swigt__p_gradido__data__TransactionBody,
  &_swigt__p_gradido__data__TransferAmount,
  &_swigt__p_int,
  &_swigt__p_long_long,
  &_swigt__p_memory__Block,
  &_swigt__p_memory__ConstBlockPtrComparator,
  &_swigt__p_short,
  &_swigt__p_signed_char,
  &_swigt__p_std__chrono__system_clock__duration,
  &_swigt__p_std__chrono__time_pointT_std__chrono__system_clock_t,
  &_swigt__p_std__shared_ptrT_KeyPairEd25519_t,
  &_swigt__p_std__shared_ptrT_SecretKeyCryptography_t,
  &_swigt__p_std__shared_ptrT_gradido__data__CommunityFriendsUpdate_t,
  &_swigt__p_std__shared_ptrT_gradido__data__CommunityRoot_t,
  &_swigt__p_std__shared_ptrT_gradido__data__ConfirmedTransaction_const_t,
  &_swigt__p_std__shared_ptrT_gradido__data__ConfirmedTransaction_t,
  &_swigt__p_std__shared_ptrT_gradido__data__GradidoCreation_t,
  &_swigt__p_std__shared_ptrT_gradido__data__GradidoDeferredTransfer_t,
  &_swigt__p_std__shared_ptrT_gradido__data__GradidoTransaction_const_t,
  &_swigt__p_std__shared_ptrT_gradido__data__GradidoTransfer_t,
  &_swigt__p_std__shared_ptrT_gradido__data__RegisterAddress_t,
  &_swigt__p_std__shared_ptrT_gradido__data__TransactionBody_const_t,
  &_swigt__p_std__shared_ptrT_memory__Block_const_t,
  &_swigt__p_std__shared_ptrT_memory__Block_t,
  &_swigt__p_std__spanT_std__byte_t,
  &_swigt__p_std__string,
  &_swigt__p_std__vectorT_gradido__data__SignaturePair_t,
  &_swigt__p_std__vectorT_std__shared_ptrT_memory__Block_const_t_t,
  &_swigt__p_std__vectorT_unsigned_char_t,
  &_swigt__p_unsigned_char,
  &_swigt__p_unsigned_int,
  &_swigt__p_unsigned_long_long,
  &_swigt__p_unsigned_short,
};

SWIGINTERN swig_cast_info _swigc__p_GradidoUnit[] = {  {&_swigt__p_GradidoUnit, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_SecretKeyCryptography[] = {  {&_swigt__p_SecretKeyCryptography, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_DecryptionException[] = {{&_swigt__p_DecryptionException, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_EncryptionException[] = {{&_swigt__p_EncryptionException, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_EncryptionKeyException[] = {{&_swigt__p_EncryptionKeyException, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_MissingEncryptionException[] = {{&_swigt__p_MissingEncryptionException, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_SecretKeyCryptographyException[] = {  {&_swigt__p_SecretKeyCryptographyException, 0, 0, 0},  {&_swigt__p_DecryptionException, _p_DecryptionExceptionTo_p_SecretKeyCryptographyException, 0, 0},  {&_swigt__p_EncryptionException, _p_EncryptionExceptionTo_p_SecretKeyCryptographyException, 0, 0},  {&_swigt__p_EncryptionKeyException, _p_EncryptionKeyExceptionTo_p_SecretKeyCryptographyException, 0, 0},  {&_swigt__p_MissingEncryptionException, _p_MissingEncryptionExceptionTo_p_SecretKeyCryptographyException, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_char[] = {  {&_swigt__p_char, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_gradido__GradidoTransactionBuilder[] = {  {&_swigt__p_gradido__GradidoTransactionBuilder, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_gradido__TransactionBodyBuilder[] = {  {&_swigt__p_gradido__TransactionBodyBuilder, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_gradido__data__CommunityFriendsUpdate[] = {  {&_swigt__p_gradido__data__CommunityFriendsUpdate, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_gradido__data__CommunityRoot[] = {  {&_swigt__p_gradido__data__CommunityRoot, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_gradido__data__ConfirmedTransaction[] = {  {&_swigt__p_gradido__data__ConfirmedTransaction, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_gradido__data__GradidoCreation[] = {  {&_swigt__p_gradido__data__GradidoCreation, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_gradido__data__GradidoDeferredTransfer[] = {  {&_swigt__p_gradido__data__GradidoDeferredTransfer, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_gradido__data__GradidoTransaction[] = {  {&_swigt__p_gradido__data__GradidoTransaction, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_gradido__data__GradidoTransfer[] = {  {&_swigt__p_gradido__data__GradidoTransfer, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_gradido__data__RegisterAddress[] = {  {&_swigt__p_gradido__data__RegisterAddress, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_gradido__data__SignatureMap[] = {  {&_swigt__p_gradido__data__SignatureMap, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_gradido__data__SignaturePair[] = {  {&_swigt__p_gradido__data__SignaturePair, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_gradido__data__Timestamp[] = {  {&_swigt__p_gradido__data__Timestamp, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_gradido__data__TimestampSeconds[] = {  {&_swigt__p_gradido__data__TimestampSeconds, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_gradido__data__TransactionBody[] = {  {&_swigt__p_gradido__data__TransactionBody, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_gradido__data__TransferAmount[] = {  {&_swigt__p_gradido__data__TransferAmount, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_int[] = {  {&_swigt__p_int, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_long_long[] = {  {&_swigt__p_long_long, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_memory__Block[] = {  {&_swigt__p_memory__Block, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_memory__ConstBlockPtrComparator[] = {  {&_swigt__p_memory__ConstBlockPtrComparator, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_short[] = {  {&_swigt__p_short, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_signed_char[] = {  {&_swigt__p_signed_char, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__chrono__system_clock__duration[] = {  {&_swigt__p_std__chrono__system_clock__duration, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__chrono__time_pointT_std__chrono__system_clock_t[] = {  {&_swigt__p_std__chrono__time_pointT_std__chrono__system_clock_t, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__shared_ptrT_KeyPairEd25519_t[] = {  {&_swigt__p_std__shared_ptrT_KeyPairEd25519_t, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__shared_ptrT_SecretKeyCryptography_t[] = {  {&_swigt__p_std__shared_ptrT_SecretKeyCryptography_t, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__shared_ptrT_gradido__data__CommunityFriendsUpdate_t[] = {  {&_swigt__p_std__shared_ptrT_gradido__data__CommunityFriendsUpdate_t, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__shared_ptrT_gradido__data__CommunityRoot_t[] = {  {&_swigt__p_std__shared_ptrT_gradido__data__CommunityRoot_t, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__shared_ptrT_gradido__data__ConfirmedTransaction_const_t[] = {  {&_swigt__p_std__shared_ptrT_gradido__data__ConfirmedTransaction_const_t, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__shared_ptrT_gradido__data__ConfirmedTransaction_t[] = {  {&_swigt__p_std__shared_ptrT_gradido__data__ConfirmedTransaction_t, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__shared_ptrT_gradido__data__GradidoCreation_t[] = {  {&_swigt__p_std__shared_ptrT_gradido__data__GradidoCreation_t, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__shared_ptrT_gradido__data__GradidoDeferredTransfer_t[] = {  {&_swigt__p_std__shared_ptrT_gradido__data__GradidoDeferredTransfer_t, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__shared_ptrT_gradido__data__GradidoTransaction_const_t[] = {  {&_swigt__p_std__shared_ptrT_gradido__data__GradidoTransaction_const_t, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__shared_ptrT_gradido__data__GradidoTransfer_t[] = {  {&_swigt__p_std__shared_ptrT_gradido__data__GradidoTransfer_t, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__shared_ptrT_gradido__data__RegisterAddress_t[] = {  {&_swigt__p_std__shared_ptrT_gradido__data__RegisterAddress_t, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__shared_ptrT_gradido__data__TransactionBody_const_t[] = {  {&_swigt__p_std__shared_ptrT_gradido__data__TransactionBody_const_t, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__shared_ptrT_memory__Block_const_t[] = {  {&_swigt__p_std__shared_ptrT_memory__Block_const_t, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__shared_ptrT_memory__Block_t[] = {  {&_swigt__p_std__shared_ptrT_memory__Block_t, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__spanT_std__byte_t[] = {  {&_swigt__p_std__spanT_std__byte_t, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__string[] = {  {&_swigt__p_std__string, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__vectorT_gradido__data__SignaturePair_t[] = {  {&_swigt__p_std__vectorT_gradido__data__SignaturePair_t, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__vectorT_std__shared_ptrT_memory__Block_const_t_t[] = {  {&_swigt__p_std__vectorT_std__shared_ptrT_memory__Block_const_t_t, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_std__vectorT_unsigned_char_t[] = {  {&_swigt__p_std__vectorT_unsigned_char_t, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_unsigned_char[] = {  {&_swigt__p_unsigned_char, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_unsigned_int[] = {  {&_swigt__p_unsigned_int, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_unsigned_long_long[] = {  {&_swigt__p_unsigned_long_long, 0, 0, 0},{0, 0, 0, 0}};
SWIGINTERN swig_cast_info _swigc__p_unsigned_short[] = {  {&_swigt__p_unsigned_short, 0, 0, 0},{0, 0, 0, 0}};

SWIGINTERN swig_cast_info *swig_cast_initial[] = {
  _swigc__p_DecryptionException,
  _swigc__p_EncryptionException,
  _swigc__p_EncryptionKeyException,
  _swigc__p_GradidoUnit,
  _swigc__p_MissingEncryptionException,
  _swigc__p_SecretKeyCryptography,
  _swigc__p_SecretKeyCryptographyException,
  _swigc__p_char,
  _swigc__p_gradido__GradidoTransactionBuilder,
  _swigc__p_gradido__TransactionBodyBuilder,
  _swigc__p_gradido__data__CommunityFriendsUpdate,
  _swigc__p_gradido__data__CommunityRoot,
  _swigc__p_gradido__data__ConfirmedTransaction,
  _swigc__p_gradido__data__GradidoCreation,
  _swigc__p_gradido__data__GradidoDeferredTransfer,
  _swigc__p_gradido__data__GradidoTransaction,
  _swigc__p_gradido__data__GradidoTransfer,
  _swigc__p_gradido__data__RegisterAddress,
  _swigc__p_gradido__data__SignatureMap,
  _swigc__p_gradido__data__SignaturePair,
  _swigc__p_gradido__data__Timestamp,
  _swigc__p_gradido__data__TimestampSeconds,
  _swigc__p_gradido__data__TransactionBody,
  _swigc__p_gradido__data__TransferAmount,
  _swigc__p_int,
  _swigc__p_long_long,
  _swigc__p_memory__Block,
  _swigc__p_memory__ConstBlockPtrComparator,
  _swigc__p_short,
  _swigc__p_signed_char,
  _swigc__p_std__chrono__system_clock__duration,
  _swigc__p_std__chrono__time_pointT_std__chrono__system_clock_t,
  _swigc__p_std__shared_ptrT_KeyPairEd25519_t,
  _swigc__p_std__shared_ptrT_SecretKeyCryptography_t,
  _swigc__p_std__shared_ptrT_gradido__data__CommunityFriendsUpdate_t,
  _swigc__p_std__shared_ptrT_gradido__data__CommunityRoot_t,
  _swigc__p_std__shared_ptrT_gradido__data__ConfirmedTransaction_const_t,
  _swigc__p_std__shared_ptrT_gradido__data__ConfirmedTransaction_t,
  _swigc__p_std__shared_ptrT_gradido__data__GradidoCreation_t,
  _swigc__p_std__shared_ptrT_gradido__data__GradidoDeferredTransfer_t,
  _swigc__p_std__shared_ptrT_gradido__data__GradidoTransaction_const_t,
  _swigc__p_std__shared_ptrT_gradido__data__GradidoTransfer_t,
  _swigc__p_std__shared_ptrT_gradido__data__RegisterAddress_t,
  _swigc__p_std__shared_ptrT_gradido__data__TransactionBody_const_t,
  _swigc__p_std__shared_ptrT_memory__Block_const_t,
  _swigc__p_std__shared_ptrT_memory__Block_t,
  _swigc__p_std__spanT_std__byte_t,
  _swigc__p_std__string,
  _swigc__p_std__vectorT_gradido__data__SignaturePair_t,
  _swigc__p_std__vectorT_std__shared_ptrT_memory__Block_const_t_t,
  _swigc__p_std__vectorT_unsigned_char_t,
  _swigc__p_unsigned_char,
  _swigc__p_unsigned_int,
  _swigc__p_unsigned_long_long,
  _swigc__p_unsigned_short,
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

SWIGINTERN swig_type_info *swig_types[56];
SWIGINTERN swig_module_info swig_module = {swig_types, 55, 0, 0, 0, 0};

