/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/gradido-blockchain-js.h"

/* Class: CompactFilter (_exports_CompactFilter) */
// jsnapi_getclass
Napi::Function _exports_CompactFilter_inst::GetClass(Napi::Env env) {
  std::map<std::string, _exports_CompactFilter_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_exports_CompactFilter_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_exports_CompactFilter_inst>::DefineClass(env, "CompactFilter", symbolTable);
}

void _exports_CompactFilter_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _exports_CompactFilter_templ::PropertyDescriptor> &members,
  std::map<std::string, _exports_CompactFilter_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_variable
  members.erase("searchDirection");
  members.insert({
    "searchDirection",
      _exports_CompactFilter_templ::InstanceAccessor("searchDirection",
        &_exports_CompactFilter_templ::_wrap_CompactFilter_searchDirection_get,
        &_exports_CompactFilter_templ::_wrap_CompactFilter_searchDirection_set,
        static_cast<napi_property_attributes>(napi_writable | napi_enumerable | napi_configurable))
    });
  // jsnapi_register_member_variable
  members.erase("transactionType");
  members.insert({
    "transactionType",
      _exports_CompactFilter_templ::InstanceAccessor("transactionType",
        &_exports_CompactFilter_templ::_wrap_CompactFilter_transactionType_get,
        &_exports_CompactFilter_templ::_wrap_CompactFilter_transactionType_set,
        static_cast<napi_property_attributes>(napi_writable | napi_enumerable | napi_configurable))
    });
  // jsnapi_register_member_variable
  members.erase("publicKeySearchType");
  members.insert({
    "publicKeySearchType",
      _exports_CompactFilter_templ::InstanceAccessor("publicKeySearchType",
        &_exports_CompactFilter_templ::_wrap_CompactFilter_publicKeySearchType_get,
        &_exports_CompactFilter_templ::_wrap_CompactFilter_publicKeySearchType_set,
        static_cast<napi_property_attributes>(napi_writable | napi_enumerable | napi_configurable))
    });
  // jsnapi_register_member_variable
  members.erase("coinCommunityIdIndex");
  members.insert({
    "coinCommunityIdIndex",
      _exports_CompactFilter_templ::InstanceAccessor("coinCommunityIdIndex",
        &_exports_CompactFilter_templ::_wrap_CompactFilter_coinCommunityIdIndex_get,
        &_exports_CompactFilter_templ::_wrap_CompactFilter_coinCommunityIdIndex_set,
        static_cast<napi_property_attributes>(napi_writable | napi_enumerable | napi_configurable))
    });
  // jsnapi_register_member_variable
  members.erase("maxTransactionNr");
  members.insert({
    "maxTransactionNr",
      _exports_CompactFilter_templ::InstanceAccessor("maxTransactionNr",
        &_exports_CompactFilter_templ::_wrap_CompactFilter_maxTransactionNr_get,
        &_exports_CompactFilter_templ::_wrap_CompactFilter_maxTransactionNr_set,
        static_cast<napi_property_attributes>(napi_writable | napi_enumerable | napi_configurable))
    });
  // jsnapi_register_member_variable
  members.erase("minTransactionNr");
  members.insert({
    "minTransactionNr",
      _exports_CompactFilter_templ::InstanceAccessor("minTransactionNr",
        &_exports_CompactFilter_templ::_wrap_CompactFilter_minTransactionNr_get,
        &_exports_CompactFilter_templ::_wrap_CompactFilter_minTransactionNr_set,
        static_cast<napi_property_attributes>(napi_writable | napi_enumerable | napi_configurable))
    });
  // jsnapi_register_member_variable
  members.erase("publicKeyIndex");
  members.insert({
    "publicKeyIndex",
      _exports_CompactFilter_templ::InstanceAccessor("publicKeyIndex",
        &_exports_CompactFilter_templ::_wrap_CompactFilter_publicKeyIndex_get,
        &_exports_CompactFilter_templ::_wrap_CompactFilter_publicKeyIndex_set,
        static_cast<napi_property_attributes>(napi_writable | napi_enumerable | napi_configurable))
    });
  // jsnapi_register_member_variable
  members.erase("pagination");
  members.insert({
    "pagination",
      _exports_CompactFilter_templ::InstanceAccessor("pagination",
        &_exports_CompactFilter_templ::_wrap_CompactFilter_pagination_get,
        &_exports_CompactFilter_templ::_wrap_CompactFilter_pagination_set,
        static_cast<napi_property_attributes>(napi_writable | napi_enumerable | napi_configurable))
    });
  // jsnapi_register_member_variable
  members.erase("timepointInterval");
  members.insert({
    "timepointInterval",
      _exports_CompactFilter_templ::InstanceAccessor("timepointInterval",
        &_exports_CompactFilter_templ::_wrap_CompactFilter_timepointInterval_get,
        &_exports_CompactFilter_templ::_wrap_CompactFilter_timepointInterval_set,
        static_cast<napi_property_attributes>(napi_writable | napi_enumerable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("toJson");
  members.insert({
    "toJson",
      _exports_CompactFilter_templ::InstanceMethod("toJson",
        &_exports_CompactFilter_templ::_wrap_CompactFilter__wrap_CompactFilter_toJson,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  /* add static class functions and variables */
  // jsnapi_register_static_function
  staticMembers.erase("lastBalanceFor");
  staticMembers.insert({
    "lastBalanceFor",
      StaticMethod("lastBalanceFor",
        &_exports_CompactFilter_templ::_wrap_CompactFilter_lastBalanceFor,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

