/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.3
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/gradido-blockchain-js.h"

/* Class: InteractionDeserialize (_exports_InteractionDeserialize) */
// jsnapi_getclass
Napi::Function _exports_InteractionDeserialize_inst::GetClass(Napi::Env env) {
  std::map<std::string, _exports_InteractionDeserialize_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_exports_InteractionDeserialize_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_exports_InteractionDeserialize_inst>::DefineClass(env, "InteractionDeserialize", symbolTable);
}

void _exports_InteractionDeserialize_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _exports_InteractionDeserialize_templ::PropertyDescriptor> &members,
  std::map<std::string, _exports_InteractionDeserialize_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("run");
  members.insert({
    "run",
      _exports_InteractionDeserialize_templ::InstanceMethod("run",
        &_exports_InteractionDeserialize_templ::_wrap_InteractionDeserialize_run,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isGradidoTransaction");
  members.insert({
    "isGradidoTransaction",
      _exports_InteractionDeserialize_templ::InstanceMethod("isGradidoTransaction",
        &_exports_InteractionDeserialize_templ::_wrap_InteractionDeserialize_isGradidoTransaction,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isTransactionBody");
  members.insert({
    "isTransactionBody",
      _exports_InteractionDeserialize_templ::InstanceMethod("isTransactionBody",
        &_exports_InteractionDeserialize_templ::_wrap_InteractionDeserialize_isTransactionBody,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isConfirmedTransaction");
  members.insert({
    "isConfirmedTransaction",
      _exports_InteractionDeserialize_templ::InstanceMethod("isConfirmedTransaction",
        &_exports_InteractionDeserialize_templ::_wrap_InteractionDeserialize_isConfirmedTransaction,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getType");
  members.insert({
    "getType",
      _exports_InteractionDeserialize_templ::InstanceMethod("getType",
        &_exports_InteractionDeserialize_templ::_wrap_InteractionDeserialize_getType,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getTransactionBody");
  members.insert({
    "getTransactionBody",
      _exports_InteractionDeserialize_templ::InstanceMethod("getTransactionBody",
        &_exports_InteractionDeserialize_templ::_wrap_InteractionDeserialize_getTransactionBody,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getGradidoTransaction");
  members.insert({
    "getGradidoTransaction",
      _exports_InteractionDeserialize_templ::InstanceMethod("getGradidoTransaction",
        &_exports_InteractionDeserialize_templ::_wrap_InteractionDeserialize_getGradidoTransaction,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getConfirmedTransaction");
  members.insert({
    "getConfirmedTransaction",
      _exports_InteractionDeserialize_templ::InstanceMethod("getConfirmedTransaction",
        &_exports_InteractionDeserialize_templ::_wrap_InteractionDeserialize_getConfirmedTransaction,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

