/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/gradido-blockchain-js.h"

/* Class: HieroTransactionId (_exports_HieroTransactionId) */
// jsnapi_getclass
Napi::Function _exports_HieroTransactionId_inst::GetClass(Napi::Env env) {
  std::map<std::string, _exports_HieroTransactionId_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_exports_HieroTransactionId_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_exports_HieroTransactionId_inst>::DefineClass(env, "HieroTransactionId", symbolTable);
}

void _exports_HieroTransactionId_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _exports_HieroTransactionId_templ::PropertyDescriptor> &members,
  std::map<std::string, _exports_HieroTransactionId_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("setScheduled");
  members.insert({
    "setScheduled",
      _exports_HieroTransactionId_templ::InstanceMethod("setScheduled",
        &_exports_HieroTransactionId_templ::_wrap_HieroTransactionId_setScheduled,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("setNonce");
  members.insert({
    "setNonce",
      _exports_HieroTransactionId_templ::InstanceMethod("setNonce",
        &_exports_HieroTransactionId_templ::_wrap_HieroTransactionId_setNonce,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getTransactionValidStart");
  members.insert({
    "getTransactionValidStart",
      _exports_HieroTransactionId_templ::InstanceMethod("getTransactionValidStart",
        &_exports_HieroTransactionId_templ::_wrap_HieroTransactionId_getTransactionValidStart,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getAccountId");
  members.insert({
    "getAccountId",
      _exports_HieroTransactionId_templ::InstanceMethod("getAccountId",
        &_exports_HieroTransactionId_templ::_wrap_HieroTransactionId_getAccountId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isScheduled");
  members.insert({
    "isScheduled",
      _exports_HieroTransactionId_templ::InstanceMethod("isScheduled",
        &_exports_HieroTransactionId_templ::_wrap_HieroTransactionId_isScheduled,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getNonce");
  members.insert({
    "getNonce",
      _exports_HieroTransactionId_templ::InstanceMethod("getNonce",
        &_exports_HieroTransactionId_templ::_wrap_HieroTransactionId_getNonce,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("toString");
  members.insert({
    "toString",
      _exports_HieroTransactionId_templ::InstanceMethod("toString",
        &_exports_HieroTransactionId_templ::_wrap_HieroTransactionId_toString,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("empty");
  members.insert({
    "empty",
      _exports_HieroTransactionId_templ::InstanceMethod("empty",
        &_exports_HieroTransactionId_templ::_wrap_HieroTransactionId_empty,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("equal");
  members.insert({
    "equal",
      _exports_HieroTransactionId_templ::InstanceMethod("equal",
        &_exports_HieroTransactionId_templ::_wrap_HieroTransactionId_equal,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("lt");
  members.insert({
    "lt",
      _exports_HieroTransactionId_templ::InstanceMethod("lt",
        &_exports_HieroTransactionId_templ::_wrap_HieroTransactionId_lt,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("toJson");
  members.insert({
    "toJson",
      _exports_HieroTransactionId_templ::InstanceMethod("toJson",
        &_exports_HieroTransactionId_templ::_wrap_HieroTransactionId__wrap_HieroTransactionId_toJson,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

