/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.3
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/gradido-blockchain-js.h"

/* Class: TimestampSeconds (_exports_TimestampSeconds) */
// jsnapi_getclass
Napi::Function _exports_TimestampSeconds_inst::GetClass(Napi::Env env) {
  std::map<std::string, _exports_TimestampSeconds_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_exports_TimestampSeconds_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_exports_TimestampSeconds_inst>::DefineClass(env, "TimestampSeconds", symbolTable);
}

void _exports_TimestampSeconds_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _exports_TimestampSeconds_templ::PropertyDescriptor> &members,
  std::map<std::string, _exports_TimestampSeconds_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("getAsTimepoint");
  members.insert({
    "getAsTimepoint",
      _exports_TimestampSeconds_templ::InstanceMethod("getAsTimepoint",
        &_exports_TimestampSeconds_templ::_wrap_TimestampSeconds_getAsTimepoint,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("equal");
  members.insert({
    "equal",
      _exports_TimestampSeconds_templ::InstanceMethod("equal",
        &_exports_TimestampSeconds_templ::_wrap_TimestampSeconds_equal,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("notEqual");
  members.insert({
    "notEqual",
      _exports_TimestampSeconds_templ::InstanceMethod("notEqual",
        &_exports_TimestampSeconds_templ::_wrap_TimestampSeconds_notEqual,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("lt");
  members.insert({
    "lt",
      _exports_TimestampSeconds_templ::InstanceMethod("lt",
        &_exports_TimestampSeconds_templ::_wrap_TimestampSeconds_lt,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("lte");
  members.insert({
    "lte",
      _exports_TimestampSeconds_templ::InstanceMethod("lte",
        &_exports_TimestampSeconds_templ::_wrap_TimestampSeconds_lte,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("gt");
  members.insert({
    "gt",
      _exports_TimestampSeconds_templ::InstanceMethod("gt",
        &_exports_TimestampSeconds_templ::_wrap_TimestampSeconds_gt,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("gte");
  members.insert({
    "gte",
      _exports_TimestampSeconds_templ::InstanceMethod("gte",
        &_exports_TimestampSeconds_templ::_wrap_TimestampSeconds_gte,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_variable
  members.erase("seconds");
  members.insert({
    "seconds",
      _exports_TimestampSeconds_templ::InstanceAccessor("seconds",
        &_exports_TimestampSeconds_templ::_wrap_TimestampSeconds_seconds_get,
        &_exports_TimestampSeconds_templ::_wrap_TimestampSeconds_seconds_set,
        static_cast<napi_property_attributes>(napi_writable | napi_enumerable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

