/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/gradido-blockchain-js.h"

/* Class: LedgerAnchor (_exports_LedgerAnchor) */
// jsnapi_getclass
Napi::Function _exports_LedgerAnchor_inst::GetClass(Napi::Env env) {
  std::map<std::string, _exports_LedgerAnchor_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_exports_LedgerAnchor_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_exports_LedgerAnchor_inst>::DefineClass(env, "LedgerAnchor", symbolTable);
}

void _exports_LedgerAnchor_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _exports_LedgerAnchor_templ::PropertyDescriptor> &members,
  std::map<std::string, _exports_LedgerAnchor_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("isHieroTransactionId");
  members.insert({
    "isHieroTransactionId",
      _exports_LedgerAnchor_templ::InstanceMethod("isHieroTransactionId",
        &_exports_LedgerAnchor_templ::_wrap_LedgerAnchor_isHieroTransactionId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isLegacyGradidoDbTransactionId");
  members.insert({
    "isLegacyGradidoDbTransactionId",
      _exports_LedgerAnchor_templ::InstanceMethod("isLegacyGradidoDbTransactionId",
        &_exports_LedgerAnchor_templ::_wrap_LedgerAnchor_isLegacyGradidoDbTransactionId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isNodeTriggeredTransactionId");
  members.insert({
    "isNodeTriggeredTransactionId",
      _exports_LedgerAnchor_templ::InstanceMethod("isNodeTriggeredTransactionId",
        &_exports_LedgerAnchor_templ::_wrap_LedgerAnchor_isNodeTriggeredTransactionId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isLegacyGradidoDbCommunityId");
  members.insert({
    "isLegacyGradidoDbCommunityId",
      _exports_LedgerAnchor_templ::InstanceMethod("isLegacyGradidoDbCommunityId",
        &_exports_LedgerAnchor_templ::_wrap_LedgerAnchor_isLegacyGradidoDbCommunityId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isLegacyGradidoDbUserId");
  members.insert({
    "isLegacyGradidoDbUserId",
      _exports_LedgerAnchor_templ::InstanceMethod("isLegacyGradidoDbUserId",
        &_exports_LedgerAnchor_templ::_wrap_LedgerAnchor_isLegacyGradidoDbUserId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isLegacyGradidoDbContributionId");
  members.insert({
    "isLegacyGradidoDbContributionId",
      _exports_LedgerAnchor_templ::InstanceMethod("isLegacyGradidoDbContributionId",
        &_exports_LedgerAnchor_templ::_wrap_LedgerAnchor_isLegacyGradidoDbContributionId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isLegacyGradidoDbTransactionLinkId");
  members.insert({
    "isLegacyGradidoDbTransactionLinkId",
      _exports_LedgerAnchor_templ::InstanceMethod("isLegacyGradidoDbTransactionLinkId",
        &_exports_LedgerAnchor_templ::_wrap_LedgerAnchor_isLegacyGradidoDbTransactionLinkId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isLegacyGradidoId");
  members.insert({
    "isLegacyGradidoId",
      _exports_LedgerAnchor_templ::InstanceMethod("isLegacyGradidoId",
        &_exports_LedgerAnchor_templ::_wrap_LedgerAnchor_isLegacyGradidoId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getType");
  members.insert({
    "getType",
      _exports_LedgerAnchor_templ::InstanceMethod("getType",
        &_exports_LedgerAnchor_templ::_wrap_LedgerAnchor_getType,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getHieroTransactionId");
  members.insert({
    "getHieroTransactionId",
      _exports_LedgerAnchor_templ::InstanceMethod("getHieroTransactionId",
        &_exports_LedgerAnchor_templ::_wrap_LedgerAnchor_getHieroTransactionId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getHieroTransactionIdCompact");
  members.insert({
    "getHieroTransactionIdCompact",
      _exports_LedgerAnchor_templ::InstanceMethod("getHieroTransactionIdCompact",
        &_exports_LedgerAnchor_templ::_wrap_LedgerAnchor_getHieroTransactionIdCompact,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getLegacyGradidoDbId");
  members.insert({
    "getLegacyGradidoDbId",
      _exports_LedgerAnchor_templ::InstanceMethod("getLegacyGradidoDbId",
        &_exports_LedgerAnchor_templ::_wrap_LedgerAnchor_getLegacyGradidoDbId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getNodeTriggeredTransactionId");
  members.insert({
    "getNodeTriggeredTransactionId",
      _exports_LedgerAnchor_templ::InstanceMethod("getNodeTriggeredTransactionId",
        &_exports_LedgerAnchor_templ::_wrap_LedgerAnchor_getNodeTriggeredTransactionId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isTheSame");
  members.insert({
    "isTheSame",
      _exports_LedgerAnchor_templ::InstanceMethod("isTheSame",
        &_exports_LedgerAnchor_templ::_wrap_LedgerAnchor_isTheSame,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("toString");
  members.insert({
    "toString",
      _exports_LedgerAnchor_templ::InstanceMethod("toString",
        &_exports_LedgerAnchor_templ::_wrap_LedgerAnchor_toString,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("empty");
  members.insert({
    "empty",
      _exports_LedgerAnchor_templ::InstanceMethod("empty",
        &_exports_LedgerAnchor_templ::_wrap_LedgerAnchor_empty,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("equal");
  members.insert({
    "equal",
      _exports_LedgerAnchor_templ::InstanceMethod("equal",
        &_exports_LedgerAnchor_templ::_wrap_LedgerAnchor_equal,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("toJson");
  members.insert({
    "toJson",
      _exports_LedgerAnchor_templ::InstanceMethod("toJson",
        &_exports_LedgerAnchor_templ::_wrap_LedgerAnchor__wrap_LedgerAnchor_toJson,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

