/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/gradido-blockchain-js.h"

/* Class: TransactionTriggerEvent (_exports_TransactionTriggerEvent) */
// jsnapi_getclass
Napi::Function _exports_TransactionTriggerEvent_inst::GetClass(Napi::Env env) {
  std::map<std::string, _exports_TransactionTriggerEvent_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_exports_TransactionTriggerEvent_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_exports_TransactionTriggerEvent_inst>::DefineClass(env, "TransactionTriggerEvent", symbolTable);
}

void _exports_TransactionTriggerEvent_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _exports_TransactionTriggerEvent_templ::PropertyDescriptor> &members,
  std::map<std::string, _exports_TransactionTriggerEvent_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("getLinkedTransactionId");
  members.insert({
    "getLinkedTransactionId",
      _exports_TransactionTriggerEvent_templ::InstanceMethod("getLinkedTransactionId",
        &_exports_TransactionTriggerEvent_templ::_wrap_TransactionTriggerEvent_getLinkedTransactionId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getType");
  members.insert({
    "getType",
      _exports_TransactionTriggerEvent_templ::InstanceMethod("getType",
        &_exports_TransactionTriggerEvent_templ::_wrap_TransactionTriggerEvent_getType,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getTargetDate");
  members.insert({
    "getTargetDate",
      _exports_TransactionTriggerEvent_templ::InstanceMethod("getTargetDate",
        &_exports_TransactionTriggerEvent_templ::_wrap_TransactionTriggerEvent_getTargetDate,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("equal");
  members.insert({
    "equal",
      _exports_TransactionTriggerEvent_templ::InstanceMethod("equal",
        &_exports_TransactionTriggerEvent_templ::_wrap_TransactionTriggerEvent_equal,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isTheSame");
  members.insert({
    "isTheSame",
      _exports_TransactionTriggerEvent_templ::InstanceMethod("isTheSame",
        &_exports_TransactionTriggerEvent_templ::_wrap_TransactionTriggerEvent_isTheSame,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

