/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/gradido-blockchain-js.h"

/* Class: HieroAccountId (_exports_HieroAccountId) */
// jsnapi_getclass
Napi::Function _exports_HieroAccountId_inst::GetClass(Napi::Env env) {
  std::map<std::string, _exports_HieroAccountId_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_exports_HieroAccountId_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_exports_HieroAccountId_inst>::DefineClass(env, "HieroAccountId", symbolTable);
}

void _exports_HieroAccountId_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _exports_HieroAccountId_templ::PropertyDescriptor> &members,
  std::map<std::string, _exports_HieroAccountId_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("getShardNum");
  members.insert({
    "getShardNum",
      _exports_HieroAccountId_templ::InstanceMethod("getShardNum",
        &_exports_HieroAccountId_templ::_wrap_HieroAccountId_getShardNum,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getRealmNum");
  members.insert({
    "getRealmNum",
      _exports_HieroAccountId_templ::InstanceMethod("getRealmNum",
        &_exports_HieroAccountId_templ::_wrap_HieroAccountId_getRealmNum,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getAccountNum");
  members.insert({
    "getAccountNum",
      _exports_HieroAccountId_templ::InstanceMethod("getAccountNum",
        &_exports_HieroAccountId_templ::_wrap_HieroAccountId_getAccountNum,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getAlias");
  members.insert({
    "getAlias",
      _exports_HieroAccountId_templ::InstanceMethod("getAlias",
        &_exports_HieroAccountId_templ::_wrap_HieroAccountId_getAlias,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("toString");
  members.insert({
    "toString",
      _exports_HieroAccountId_templ::InstanceMethod("toString",
        &_exports_HieroAccountId_templ::_wrap_HieroAccountId_toString,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("empty");
  members.insert({
    "empty",
      _exports_HieroAccountId_templ::InstanceMethod("empty",
        &_exports_HieroAccountId_templ::_wrap_HieroAccountId_empty,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("equal");
  members.insert({
    "equal",
      _exports_HieroAccountId_templ::InstanceMethod("equal",
        &_exports_HieroAccountId_templ::_wrap_HieroAccountId_equal,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("toJson");
  members.insert({
    "toJson",
      _exports_HieroAccountId_templ::InstanceMethod("toJson",
        &_exports_HieroAccountId_templ::_wrap_HieroAccountId__wrap_HieroAccountId_toJson,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

