/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.6
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/gradido-blockchain-js.h"

/* Class: CompleteTransaction (_exports_CompleteTransaction) */
// jsnapi_getclass
Napi::Function _exports_CompleteTransaction_inst::GetClass(Napi::Env env) {
  std::map<std::string, _exports_CompleteTransaction_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_exports_CompleteTransaction_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_exports_CompleteTransaction_inst>::DefineClass(env, "CompleteTransaction", symbolTable);
}

void _exports_CompleteTransaction_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _exports_CompleteTransaction_templ::PropertyDescriptor> &members,
  std::map<std::string, _exports_CompleteTransaction_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("initFromGrdw");
  members.insert({
    "initFromGrdw",
      _exports_CompleteTransaction_templ::InstanceMethod("initFromGrdw",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_initFromGrdw,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("initFromProtobuf");
  members.insert({
    "initFromProtobuf",
      _exports_CompleteTransaction_templ::InstanceMethod("initFromProtobuf",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction__wrap_CompleteTransaction_initFromProtobuf,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("validate");
  members.insert({
    "validate",
      _exports_CompleteTransaction_templ::InstanceMethod("validate",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction__wrap_CompleteTransaction_validate,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getId");
  members.insert({
    "getId",
      _exports_CompleteTransaction_templ::InstanceMethod("getId",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getId,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getConfirmedAt");
  members.insert({
    "getConfirmedAt",
      _exports_CompleteTransaction_templ::InstanceMethod("getConfirmedAt",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getConfirmedAt,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getRunningHash");
  members.insert({
    "getRunningHash",
      _exports_CompleteTransaction_templ::InstanceMethod("getRunningHash",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getRunningHash,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getLedgerAnchor");
  members.insert({
    "getLedgerAnchor",
      _exports_CompleteTransaction_templ::InstanceMethod("getLedgerAnchor",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getLedgerAnchor,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getAccountBalances");
  members.insert({
    "getAccountBalances",
      _exports_CompleteTransaction_templ::InstanceMethod("getAccountBalances",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getAccountBalances,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getDecayedAccountBalance");
  members.insert({
    "getDecayedAccountBalance",
      _exports_CompleteTransaction_templ::InstanceMethod("getDecayedAccountBalance",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction__wrap_CompleteTransaction_getDecayedAccountBalance,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getBalanceDerivationType");
  members.insert({
    "getBalanceDerivationType",
      _exports_CompleteTransaction_templ::InstanceMethod("getBalanceDerivationType",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getBalanceDerivationType,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isBalanceNodeComputed");
  members.insert({
    "isBalanceNodeComputed",
      _exports_CompleteTransaction_templ::InstanceMethod("isBalanceNodeComputed",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_isBalanceNodeComputed,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isBalanceExternComputed");
  members.insert({
    "isBalanceExternComputed",
      _exports_CompleteTransaction_templ::InstanceMethod("isBalanceExternComputed",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_isBalanceExternComputed,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isInvolved");
  members.insert({
    "isInvolved",
      _exports_CompleteTransaction_templ::InstanceMethod("isInvolved",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_isInvolved,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isBalanceUpdated");
  members.insert({
    "isBalanceUpdated",
      _exports_CompleteTransaction_templ::InstanceMethod("isBalanceUpdated",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_isBalanceUpdated,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getSignatureMap");
  members.insert({
    "getSignatureMap",
      _exports_CompleteTransaction_templ::InstanceMethod("getSignatureMap",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getSignatureMap,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getBodyBytes");
  members.insert({
    "getBodyBytes",
      _exports_CompleteTransaction_templ::InstanceMethod("getBodyBytes",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getBodyBytes,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getCommunityUuid");
  members.insert({
    "getCommunityUuid",
      _exports_CompleteTransaction_templ::InstanceMethod("getCommunityUuid",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getCommunityUuid,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getPairingLedgerAnchor");
  members.insert({
    "getPairingLedgerAnchor",
      _exports_CompleteTransaction_templ::InstanceMethod("getPairingLedgerAnchor",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getPairingLedgerAnchor,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isTransfer");
  members.insert({
    "isTransfer",
      _exports_CompleteTransaction_templ::InstanceMethod("isTransfer",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_isTransfer,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isCreation");
  members.insert({
    "isCreation",
      _exports_CompleteTransaction_templ::InstanceMethod("isCreation",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_isCreation,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isCommunityFriendsUpdate");
  members.insert({
    "isCommunityFriendsUpdate",
      _exports_CompleteTransaction_templ::InstanceMethod("isCommunityFriendsUpdate",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_isCommunityFriendsUpdate,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isRegisterAddress");
  members.insert({
    "isRegisterAddress",
      _exports_CompleteTransaction_templ::InstanceMethod("isRegisterAddress",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_isRegisterAddress,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isDeferredTransfer");
  members.insert({
    "isDeferredTransfer",
      _exports_CompleteTransaction_templ::InstanceMethod("isDeferredTransfer",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_isDeferredTransfer,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isCommunityRoot");
  members.insert({
    "isCommunityRoot",
      _exports_CompleteTransaction_templ::InstanceMethod("isCommunityRoot",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_isCommunityRoot,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isRedeemDeferredTransfer");
  members.insert({
    "isRedeemDeferredTransfer",
      _exports_CompleteTransaction_templ::InstanceMethod("isRedeemDeferredTransfer",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_isRedeemDeferredTransfer,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("isTimeoutDeferredTransfer");
  members.insert({
    "isTimeoutDeferredTransfer",
      _exports_CompleteTransaction_templ::InstanceMethod("isTimeoutDeferredTransfer",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_isTimeoutDeferredTransfer,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getTransactionType");
  members.insert({
    "getTransactionType",
      _exports_CompleteTransaction_templ::InstanceMethod("getTransactionType",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getTransactionType,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getAmount");
  members.insert({
    "getAmount",
      _exports_CompleteTransaction_templ::InstanceMethod("getAmount",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getAmount,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getCoinCommunityUuid");
  members.insert({
    "getCoinCommunityUuid",
      _exports_CompleteTransaction_templ::InstanceMethod("getCoinCommunityUuid",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getCoinCommunityUuid,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("hasTransferAmount");
  members.insert({
    "hasTransferAmount",
      _exports_CompleteTransaction_templ::InstanceMethod("hasTransferAmount",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_hasTransferAmount,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getMemos");
  members.insert({
    "getMemos",
      _exports_CompleteTransaction_templ::InstanceMethod("getMemos",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getMemos,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getCreatedAt");
  members.insert({
    "getCreatedAt",
      _exports_CompleteTransaction_templ::InstanceMethod("getCreatedAt",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getCreatedAt,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getCrossGroupType");
  members.insert({
    "getCrossGroupType",
      _exports_CompleteTransaction_templ::InstanceMethod("getCrossGroupType",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getCrossGroupType,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getOtherCommunityUuid");
  members.insert({
    "getOtherCommunityUuid",
      _exports_CompleteTransaction_templ::InstanceMethod("getOtherCommunityUuid",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getOtherCommunityUuid,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getSenderPublicKey");
  members.insert({
    "getSenderPublicKey",
      _exports_CompleteTransaction_templ::InstanceMethod("getSenderPublicKey",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getSenderPublicKey,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getRecipientPublicKey");
  members.insert({
    "getRecipientPublicKey",
      _exports_CompleteTransaction_templ::InstanceMethod("getRecipientPublicKey",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getRecipientPublicKey,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getRegisteredUser");
  members.insert({
    "getRegisteredUser",
      _exports_CompleteTransaction_templ::InstanceMethod("getRegisteredUser",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getRegisteredUser,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getRegisteredAccount");
  members.insert({
    "getRegisteredAccount",
      _exports_CompleteTransaction_templ::InstanceMethod("getRegisteredAccount",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getRegisteredAccount,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getRegisteredAddressType");
  members.insert({
    "getRegisteredAddressType",
      _exports_CompleteTransaction_templ::InstanceMethod("getRegisteredAddressType",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getRegisteredAddressType,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getRegisteredDerivationIndex");
  members.insert({
    "getRegisteredDerivationIndex",
      _exports_CompleteTransaction_templ::InstanceMethod("getRegisteredDerivationIndex",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getRegisteredDerivationIndex,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getRegisteredNameHash");
  members.insert({
    "getRegisteredNameHash",
      _exports_CompleteTransaction_templ::InstanceMethod("getRegisteredNameHash",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getRegisteredNameHash,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getCommunityRootPublicKey");
  members.insert({
    "getCommunityRootPublicKey",
      _exports_CompleteTransaction_templ::InstanceMethod("getCommunityRootPublicKey",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getCommunityRootPublicKey,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getAuf");
  members.insert({
    "getAuf",
      _exports_CompleteTransaction_templ::InstanceMethod("getAuf",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getAuf,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getGmw");
  members.insert({
    "getGmw",
      _exports_CompleteTransaction_templ::InstanceMethod("getGmw",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getGmw,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getCreationTargetDate");
  members.insert({
    "getCreationTargetDate",
      _exports_CompleteTransaction_templ::InstanceMethod("getCreationTargetDate",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getCreationTargetDate,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getDeferredTransferTimeoutDuration");
  members.insert({
    "getDeferredTransferTimeoutDuration",
      _exports_CompleteTransaction_templ::InstanceMethod("getDeferredTransferTimeoutDuration",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getDeferredTransferTimeoutDuration,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getPreviousTx");
  members.insert({
    "getPreviousTx",
      _exports_CompleteTransaction_templ::InstanceMethod("getPreviousTx",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getPreviousTx,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getSenderCommunityUuidString");
  members.insert({
    "getSenderCommunityUuidString",
      _exports_CompleteTransaction_templ::InstanceMethod("getSenderCommunityUuidString",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getSenderCommunityUuidString,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getRecipientCommunityUuidString");
  members.insert({
    "getRecipientCommunityUuidString",
      _exports_CompleteTransaction_templ::InstanceMethod("getRecipientCommunityUuidString",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction_getRecipientCommunityUuidString,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getAccountBalance");
  members.insert({
    "getAccountBalance",
      _exports_CompleteTransaction_templ::InstanceMethod("getAccountBalance",
        &_exports_CompleteTransaction_templ::_wrap_CompleteTransaction__wrap_CompleteTransaction_getAccountBalance,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

