/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG JSE (https://www.swig.org).
 * Version 5.0.3
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#include "swig/gradido-blockchain-js.h"

/* Class: EncryptedMemo (_exports_EncryptedMemo) */
// jsnapi_getclass
Napi::Function _exports_EncryptedMemo_inst::GetClass(Napi::Env env) {
  std::map<std::string, _exports_EncryptedMemo_templ::PropertyDescriptor> members, staticMembers;
  GetMembers(env, members, staticMembers);
  
  std::vector<_exports_EncryptedMemo_inst::PropertyDescriptor> symbolTable;
  for (auto it = members.begin(); it != members.end(); it++)
  symbolTable.push_back(it->second);
  for (auto it = staticMembers.begin(); it != staticMembers.end(); it++)
  symbolTable.push_back(it->second);
  
  return Napi::ObjectWrap<_exports_EncryptedMemo_inst>::DefineClass(env, "EncryptedMemo", symbolTable);
}

void _exports_EncryptedMemo_inst::GetMembers(
  Napi::Env env,
  std::map<std::string, _exports_EncryptedMemo_templ::PropertyDescriptor> &members,
  std::map<std::string, _exports_EncryptedMemo_templ::PropertyDescriptor> &staticMembers
  ) {
  std::map<std::string, SWIG_NAPI_ObjectWrap_templ<SWIG_NAPI_ObjectWrap_inst>::PropertyDescriptor> baseMembers, baseStaticMembers;
  SWIG_NAPI_ObjectWrap_inst::GetMembers(env, baseMembers, baseStaticMembers);
  members.insert(baseMembers.begin(), baseMembers.end());
  staticMembers.insert(staticMembers.begin(), staticMembers.end());
  
  /* register wrapper functions */
  // jsnapi_register_member_function
  members.erase("getKeyType");
  members.insert({
    "getKeyType",
      _exports_EncryptedMemo_templ::InstanceMethod("getKeyType",
        &_exports_EncryptedMemo_templ::_wrap_EncryptedMemo_getKeyType,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("getMemo");
  members.insert({
    "getMemo",
      _exports_EncryptedMemo_templ::InstanceMethod("getMemo",
        &_exports_EncryptedMemo_templ::_wrap_EncryptedMemo_getMemo,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("equal");
  members.insert({
    "equal",
      _exports_EncryptedMemo_templ::InstanceMethod("equal",
        &_exports_EncryptedMemo_templ::_wrap_EncryptedMemo_equal,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  // jsnapi_register_member_function
  members.erase("decrypt");
  members.insert({
    "decrypt",
      _exports_EncryptedMemo_templ::InstanceMethod("decrypt",
        &_exports_EncryptedMemo_templ::_wrap_EncryptedMemo__wrap_EncryptedMemo_decrypt,
        static_cast<napi_property_attributes>(napi_writable | napi_configurable))
    });
  
  /* add static class functions and variables */
  
  
#ifndef NAPI_CPP_EXCEPTIONS
  goto fail;
fail:
  return;
#endif
}

