import { execSync } from 'node:child_process'

const gitBranch = execSync('git branch --show-current').toString().trim();
const date = new Date().toISOString();

const GIT_DEFINE = `-DGIT_BRANCH="// Generated by SWIG on branch ${gitBranch} ${date}"`;

const swigArgs = [
  '-warnall',
  '-Wall',
  GIT_DEFINE,
  '-javascript',
  '-typescript',
  '-napi',
  '-c++',
  '-split',
  '-exports', '../index.js',
  '-Ideps/gradido_blockchain/src',
  '-Ideps/gradido_blockchain/include',
  '-o', 'swig/gradido-blockchain-js.cxx',
  '-outdir', 'swig',
  'src/gradido-blockchain-js.i'
];

const cmd = ['swig-jse', ...swigArgs].join(' ');
execSync(cmd, { stdio: 'inherit' });
