name: Build Native Addon Prebuilds

on:
  push:
    #tags:
    # - 'v*'  # Trigger nur bei Versionstags wie v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["linux/amd64", "linux/arm64", "windows/amd64", "windows/arm64", "darwin/amd64", "darwin/arm64", "alpine/amd64"]
    name: Build for ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.7

      - name: install bun 
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build prebuild binary
        uses: cross-platform-actions/action@v0.28.0
        with:
          target: ${{ matrix.platform }}
          command: bun buildify

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: prebuild-${{ matrix.platform }}
          path: prebuilds/**
